export const FAN_BADGE_NFT_ABI = [
  "constructor()",
  "error ERC721EnumerableForbiddenBatchMint()",
  "error ERC721IncorrectOwner(address,uint256,address)",
  "error ERC721InsufficientApproval(address,uint256)",
  "error ERC721InvalidApprover(address)",
  "error ERC721InvalidOperator(address)",
  "error ERC721InvalidOwner(address)",
  "error ERC721InvalidReceiver(address)",
  "error ERC721InvalidSender(address)",
  "error ERC721NonexistentToken(uint256)",
  "error ERC721OutOfBoundsIndex(address,uint256)",
  "error OwnableInvalidOwner(address)",
  "error OwnableUnauthorizedAccount(address)",
  "event Approval(address indexed,address indexed,uint256 indexed)",
  "event ApprovalForAll(address indexed,address indexed,bool)",
  "event BadgeMinted(address indexed,uint256)",
  "event BadgeUpgraded(uint256 indexed,uint256)",
  "event OwnershipTransferred(address indexed,address indexed)",
  "event Transfer(address indexed,address indexed,uint256 indexed)",
  "function approve(address,uint256)",
  "function badgeLevels(uint256) view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function getApproved(uint256) view returns (address)",
  "function isApprovedForAll(address,address) view returns (bool)",
  "function mint()",
  "function name() view returns (string)",
  "function owner() view returns (address)",
  "function ownerOf(uint256) view returns (address)",
  "function pointSystem() view returns (address)",
  "function renounceOwnership()",
  "function safeTransferFrom(address,address,uint256)",
  "function safeTransferFrom(address,address,uint256,bytes)",
  "function setApprovalForAll(address,bool)",
  "function setPointSystem(address)",
  "function supportsInterface(bytes4) view returns (bool)",
  "function symbol() view returns (string)",
  "function tokenByIndex(uint256) view returns (uint256)",
  "function tokenOfOwnerByIndex(address,uint256) view returns (uint256)",
  "function tokenURI(uint256) view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function transferFrom(address,address,uint256)",
  "function transferOwnership(address)",
  "function upgrade(uint256)"
] as const;

export const POINT_SYSTEM_ABI = [
  "constructor(address)",
  "error OwnableInvalidOwner(address)",
  "error OwnableUnauthorizedAccount(address)",
  "event CheckedIn(address indexed,uint256)",
  "event Interacted(address indexed,string,uint256)",
  "event OwnershipTransferred(address indexed,address indexed)",
  "event PointsSpent(address indexed,uint256)",
  "function POINTS_PER_CHECKIN() view returns (uint256)",
  "function POINTS_PER_LIKE() view returns (uint256)",
  "function POINTS_PER_VOTE() view returns (uint256)",
  "function UPGRADE_COST_BASE() view returns (uint256)",
  "function badgeNFT() view returns (address)",
  "function checkIn()",
  "function getPoints(address) view returns (uint256)",
  "function interact(string)",
  "function owner() view returns (address)",
  "function renounceOwnership()",
  "function transferOwnership(address)",
  "function upgradeBadge()",
  "function users(address) view returns (uint256,uint256)"
] as const;

export const FAN_BADGE_NFT_ADDRESS = "0x0000000000000000000000000000000000000000"; // TODO: Replace with deployed address
export const POINT_SYSTEM_ADDRESS = "0x0000000000000000000000000000000000000000"; // TODO: Replace with deployed address
